force-app/main/default/objects/List_Metadata__c/List_Metadata__c.object-meta.xml
<CustomObject>
    <description>Object defines metadata for dependent 2 level list in LWC</description>
    <label>List Metadata</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>List Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Metadata__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Active True display in a list, control what value to show on selector component</description>
    <inlineHelpText>Control what value to show on selector component</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Metadata__c/fields/Child_Label__c.field-meta.xml
<CustomField>
    <fullName>Child_Label__c</fullName>
    <description>Clild Label to display</description>
    <label>Child Label</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/List_Metadata__c/fields/Child_Value__c.field-meta.xml
<CustomField>
    <fullName>Child_Value__c</fullName>
    <description>Child field Value</description>
    <label>Child Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/List_Metadata__c/fields/Reason_Label__c.field-meta.xml
<CustomField>
    <fullName>Reason_Label__c</fullName>
    <description>Label data to display</description>
    <inlineHelpText>Label data to display</inlineHelpText>
    <label>Reason Label</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/List_Metadata__c/fields/Reason_Value__c.field-meta.xml
<CustomField>
    <fullName>Reason_Value__c</fullName>
    <description>Main control field</description>
    <label>Reason Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ES_ComboListManagerCtrl.cls
/**
 * Supporting class controller for LWC escomboMainList and escomboChildList
 * 
 * Author: A.I.
 */
public without sharing class ES_ComboListManagerCtrl {

    @AuraEnabled(cacheable=true)
    public static List<List_Metadata__c> findParentComboList() {
        List<List_Metadata__c> lmList = [SELECT Id, Name, Reason_Value__c, Reason_Label__c 
                                        FROM List_Metadata__c WHERE Active__c = true];
        Map<String,List_Metadata__c> lmMap = new Map<String,List_Metadata__c>();
        for (List_Metadata__c lm : lmList){
            lmMap.put(lm.Reason_Value__c,lm);
        }
        return (List<List_Metadata__c>)lmMap.values();
    }
    // Give Value query all list
    @AuraEnabled(cacheable=true)
    public static List<List_Metadata__c> findChildComboList(String val) {
        List<List_Metadata__c> lmList = [SELECT Id, Name, Child_Value__c, Child_Label__c 
                                        FROM List_Metadata__c WHERE Reason_Value__c =: val];
        return lmList;
    }

    // Save new child list value under Other
    // Admin can validate and move parent later on
    @AuraEnabled
    public static void saveChildListValue(String val){
        List_Metadata__c lm = new List_Metadata__c();
        lm.Child_Label__c = val;
        lm.Child_Value__c = val;
        lm.Reason_Value__c = 'Other';
        lm.Reason_Label__c = 'Other';
        insert lm;
    }
}