force-app/main/default/objects/List_Metadata__c/List_Metadata__c.object-meta.xml
<CustomObject>
    <description>Object defines metadata for dependent 2 level list in LWC</description>
    <label>List Metadata</label>
    <nameField>
        <displayFormat>E-{00000}</displayFormat>
        <label>List Metadata Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>List Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/List_Metadata__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Active True display in a list, control what value to show on selector component</description>
    <inlineHelpText>Control what value to show on selector component</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/List_Metadata__c/fields/Child_Label__c.field-meta.xml
<CustomField>
    <fullName>Child_Label__c</fullName>
    <description>Clild Label to display</description>
    <label>Child Label</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/List_Metadata__c/fields/Child_Value__c.field-meta.xml
<CustomField>
    <fullName>Child_Value__c</fullName>
    <description>Child field Value</description>
    <label>Child Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/List_Metadata__c/fields/Reason_Label__c.field-meta.xml
<CustomField>
    <fullName>Reason_Label__c</fullName>
    <description>Label data to display</description>
    <inlineHelpText>Label data to display</inlineHelpText>
    <label>Reason Label</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/List_Metadata__c/fields/Reason_Value__c.field-meta.xml
<CustomField>
    <fullName>Reason_Value__c</fullName>
    <description>Main control field</description>
    <label>Reason Value</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ES_ComboListManagerCtrlTest.cls
/**
 * Test class controller for LWC escomboMainList and escomboChildList
 * 
 * Author: A.I.
 */
@isTest
public class ES_ComboListManagerCtrlTest {
    @testSetUp
    static void setUpData(){
        List<List_Metadata__c> lst = new List<List_Metadata__c>();

        for (Integer i=1; i<3; i++){
            for(Integer j=1; j<3; j++){
                List_Metadata__c lm = new List_Metadata__c();
                lm.Active__c = true;
                lm.Reason_Value__c = 'Parent '+i;
                lm.Reason_Label__c = 'Parent '+i;
                lm.Child_Value__c = 'Child '+i+' : '+j;
                lm.Child_Label__c = 'Child '+i+ ' : '+j;
                lst.add(lm);
            }
        }
        List_Metadata__c lm = new List_Metadata__c();
        lm.Active__c = true;
        lm.Reason_Value__c = 'Other';
        lm.Reason_Label__c = 'Other';
        lst.add(lm);

        insert lst;
    }

    @isTest
    static void findParentComboListTest(){
        Test.startTest();
        List<List_Metadata__c> lst = ES_ComboListManagerCtrl.findParentComboList() ;
        Test.stopTest();

        system.assertEquals(3,lst.size());
    }

    @isTest
    static void findChildComboListTest(){
        Test.startTest();
        List<List_Metadata__c> lst = ES_ComboListManagerCtrl.findChildComboList('Parent 1');
        Test.stopTest();
        system.assertEquals(2,lst.size());
    }

    @isTest
    static void saveChildListValueTest(){
        Test.startTest();
        // This willl create single entry for Other - parent and Neew Val as Child
        ES_ComboListManagerCtrl.saveChildListValue('New Val');
        Test.stopTest();
        // Query new data
        List<List_Metadata__c> lst = [SELECT Id, Active__c, Reason_Value__c, Child_Value__c, Child_Label__c 
                                        FROM List_Metadata__c WHERE Child_Value__c = 'New Val'];
        system.assertEquals(1,lst.size());
        List_Metadata__c pick = (List_Metadata__c)lst[0];
        system.assertNotEquals(null,pick);
        system.assertEquals(false,pick.Active__c); // New values added NOT Active for Admin to edit
        system.assertEquals('Other',pick.Reason_Value__c);
    }
}